In [1]:
import numpy as np

In [2]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
arr_2d[0][1]

10

In [5]:
arr_2d[2][2]

45

In [6]:
arr_2d[0]

array([ 5, 10, 15])

In [8]:
arr_2d[2]

array([35, 40, 45])

In [9]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [10]:
arr_2d[0,1]

10

In [11]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [12]:
arr_2d[0:2,1:3]#lấy tất cả giá trị ở vị trí từ dòng 0 đến 1 và cột từ 1 đến 2

array([[10, 15],
       [25, 30]])

In [13]:
#lấy ra mảng bao gồm giá trị 25,30,40,45

In [14]:
arr_2d[1:,1:]


array([[25, 30],
       [40, 45]])

In [15]:
arr_2d>20

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [16]:
bool_arr=arr_2d>20

In [17]:
bool_arr

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [18]:
arr_2d[bool_arr]

array([25, 30, 35, 40, 45])

In [19]:
arr_2d[arr_2d>20]

array([25, 30, 35, 40, 45])

In [20]:
arr_2d[arr_2d<10]

array([5])

In [21]:
arr_dachieu=np.arange(50).reshape(5,10)

In [22]:
arr_dachieu

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
#bài tập lấy mảng bao gồm 13,14,23,24

In [24]:
arr_dachieu[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [25]:
arr_dachieu[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
arr_dachieu[1:3,3:5]

array([[13, 14],
       [23, 24]])