In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
array=np.array(my_list)

In [4]:
array #array là một cái mảng 1 chiều có 3 giá trị là 1 2 và 3

array([1, 2, 3])

In [5]:
my_list2=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
arr_3d=np.array(my_list2)

In [7]:
arr_3d #mảng 3 chiều có 3 dòng và 3 cột

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.arange(0,10) #tạo ra một mảng 1 chiều có giá trị bắt đầu và kết thúc do người dùng nhập vào

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,50) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3) #shape đại diện cho khái niệm cấu trúc của mảng. Có nghĩa là mảng có bao nhiêu dòng và bao nhiêu cột

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10) #hàm trả về các số cách đều nhau trong một khoảng không gian cố định

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [20]:
np.eye(5) #tạo ra một ma trận đơn vị

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#mảng ngẫu nhiên

In [22]:
np.random.rand(5)

array([0.32696973, 0.08090137, 0.07208847, 0.53651461, 0.23088684])

In [23]:
np.random.rand(5)

array([0.21518254, 0.32454146, 0.87373785, 0.62723576, 0.42279484])

In [24]:
np.random.rand(5,5)

array([[0.126121  , 0.28795433, 0.30016713, 0.20374335, 0.90623624],
       [0.83917233, 0.37739561, 0.33615743, 0.52756023, 0.79735498],
       [0.45746049, 0.52393232, 0.56248413, 0.41869857, 0.7118348 ],
       [0.95709086, 0.42974695, 0.29476973, 0.07919328, 0.80450069],
       [0.37891915, 0.338     , 0.6579242 , 0.15831543, 0.46884941]])

In [25]:
#mảng ngẫu nhiên nhưng là số nguyên

In [26]:
np.random.randint(1,100)

57

In [27]:
np.random.randint(1,100,10)

array([87, 87, 24,  5, 95,  6, 63,  1, 19, 62])

In [29]:
np.random.randint(1,100,50)

array([62, 35, 52, 19, 42, 27, 19, 58, 93, 58, 13, 93, 23,  1, 57, 52,  7,
       53, 59, 70, 95, 25, 40, 45, 19, 34, 99, 45, 32, 81, 95, 33, 56, 88,
       25, 93, 55, 72, 50, 98, 33, 36, 53,  2, 88, 23, 68, 90, 30, 69])

In [38]:
#hàm tái cấu trúc một mảng
arr=np.random.randint(1,100,30)

In [39]:
arr

array([46, 60, 74, 87, 12, 37, 31, 76, 84, 14, 93, 34, 62, 67,  9, 53,  5,
       81, 64, 65, 55, 94, 74,  2,  3, 88, 18, 33, 45, 70])

In [41]:
arr.reshape(6,5)

array([[46, 60, 74, 87, 12],
       [37, 31, 76, 84, 14],
       [93, 34, 62, 67,  9],
       [53,  5, 81, 64, 65],
       [55, 94, 74,  2,  3],
       [88, 18, 33, 45, 70]])

In [42]:
arr.max()

94

In [43]:
arr.min()

2

In [44]:
arr.argmax()

21

In [45]:
arr.argmin()

23

In [47]:
arr.shape

(30,)

In [48]:
arr=arr.reshape(6,5)

In [49]:
arr.shape

(6, 5)

In [51]:
arr.dtype

dtype('int32')

In [55]:
from numpy.random import randint

In [53]:
randint(2,10)

6