In [1]:
import numpy as np

In [8]:
arr=np.arange(11,21)

In [9]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[8] #8 là vị trí của giá trị trong mảng

19

In [11]:
arr[1:5]

array([12, 13, 14, 15])

In [12]:
arr[:5]

array([11, 12, 13, 14, 15])

In [13]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[0:5]=100 

In [16]:
arr

array([100, 100, 100, 100, 100,  16,  17,  18,  19,  20])

In [17]:
arr=np.arange(11,21)

In [18]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
# lỗi copy và khuyến cáo không dùng phép gán này khi muốn tạo mảng mới từ một mảng cũ mà phải dùng lệnh copy
arr2=arr[0:6] #theo cách nghĩ bình thường là tôi đã tạo một mảng arr2 mới với giá trị của arr từ 11 đến 16

In [20]:
arr2

array([11, 12, 13, 14, 15, 16])

In [21]:
arr2[:]=100

In [22]:
arr2

array([100, 100, 100, 100, 100, 100])

In [23]:
arr

array([100, 100, 100, 100, 100, 100,  17,  18,  19,  20])

In [ ]:
# copy đúng

In [24]:
arr_copy=arr.copy()

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100,  17,  18,  19,  20])

In [26]:
arr

array([100, 100, 100, 100, 100, 100,  17,  18,  19,  20])

In [27]:
arr_copy[:]=0

In [28]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
arr

array([100, 100, 100, 100, 100, 100,  17,  18,  19,  20])